@startuml activity
header activity diagrams
Title Заказ товара

start
:Поиск товара;
:Выбор товара;
:Добавление в корзину;

repeat
  :Переход к оформлению заказа;
  :Выбор способа доставки;
  :Выбор способа оплаты;
  
  repeat while (Доступен выбранный способ доставки?) is (нет)
    ->да;

:Подтверждение заказа;
:Оплата заказа;

repeat
  repeat while (Проверка оплаты) is (не подтверждена) not (подтверждена)
  
:Формирование заказа продавцом;
:Передача в службу доставки;

fork
  :Уведомление клиента о статусе;
  :Подготовка товара к отправке;
  :Отправка товара;
fork again
  :Отслеживание доставки клиентом;
end fork

:Получение товара клиентом;
if (Клиент доволен?) then (да)
  :Завершение заказа;
  :Возможность оставить отзыв;
else (нет)
  :Инициация возврата;
  :Обработка возврата продавцом;
endif

stop
@enduml
