@startuml usecases

actor "Клиент" as Client
actor "Продавец" as Seller
actor "Владелец пункта выдачи" as PointOwner

left to right direction

Client-->(Вход в систему / Выход из системы)
Seller-->(Вход в систему / Выход из системы)
PointOwner-->(Вход в систему / Выход из системы)

Client-->(Просмотр товаров)
Client-->(Добавить товар в корзину)
Client-->(Оформить заказ)
Client-->(Оплатить заказ)
Client-->(Отслеживать статус заказа)
Client-->(Оставить отзыв)
Client-->(Просмотр заказов)

Seller-->(Добавить товар)
Seller-->(Редактировать товар)
Seller-->(Удалить товар)
Seller-->(Просмотр заказов)
Seller-->(Обработать заказ)
Seller-->(Отправить товар)

PointOwner-->(Просмотр заказов)
PointOwner-->(Подтвердить получение товара)
PointOwner-->(Отправить товар клиенту)

(Добавить товар)<..>(Добавить описание товара): <option>
(Добавить товар)<..>(Загрузить изображение товара): <option>
(Оформить заказ)<..>(Проверить наличие товара): <includes>
(Оформить заказ)<..>(Подтвердить наличие адреса доставки): <includes>
(Оплатить заказ)<..>(Оплата наличными): <includes>
(Отслеживать статус заказа)<..>(Получить обновления статуса): <includes>

@enduml
